<a href="https://colab.research.google.com/github/rafidhadizuhair/Laporan-Data-Mining-Rafid-Hadi-Zuhair_241011401361/blob/main/Peretumuan_3_dan_Tugas_Latihan_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
from scipy.spatial.distance import euclidean, cityblock, minkowski

# 1. Data contoh sederhana
A = np.array([2, 3])
B = np.array([5, 7])

# Perhitungan berbagai metode jarak
euc_dist = euclidean(A, B)
man_dist = cityblock(A, B)
min_dist = minkowski(A, B, p=3)  # Parameter p sering disebut r dalam rumus matematika

print("--- Hasil Perhitungan Dasar ---")
print(f"Euclidean Distance : {euc_dist:.2f}") # Hasil: 5.00
print(f"Manhattan Distance : {man_dist:.2f}") # Hasil: 7.00
print(f"Minkowski (p=3)    : {min_dist:.2f}") # Hasil: 4.50

# 2. Perbandingan dengan data berskala besar (Efek Skala)
# Contoh kasus: Fitur 1 (misal: usia) vs Fitur 2 (misal: pendapatan dalam jutaan)
A_scaled = np.array([2, 2_000_000])
B_scaled = np.array([5, 7_000_000])

print("\n--- Analisis Dampak Skala ---")
print("Tanpa normalisasi:")
print(f"Euclidean: {euclidean(A_scaled, B_scaled):.2f}")

# Catatan: Output di atas akan sangat besar karena didominasi oleh fitur pendapatan (fitur kedua).

--- Hasil Perhitungan Dasar ---
Euclidean Distance : 5.00
Manhattan Distance : 7.00
Minkowski (p=3)    : 4.50

--- Analisis Dampak Skala ---
Tanpa normalisasi:
Euclidean: 5000000.00


In [8]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from scipy.spatial.distance import euclidean

# 1. Menyiapkan Data dengan skala yang berbeda jauh
# Kolom 1: Usia/Rating (skala kecil), Kolom 2: Pendapatan (skala besar)
data = np.array([
    [2, 2_000_000],
    [5, 7_000_000],
    [3, 5_000_000],
    [8, 12_000_000]
])

# 2. Min-Max Normalization (Mengubah range menjadi 0 sampai 1)
scaler_minmax = MinMaxScaler()
data_minmax = scaler_minmax.fit_transform(data)

# 3. Z-Score Normalization (Standardization: Mean=0, StdDev=1)
scaler_zscore = StandardScaler()
data_zscore = scaler_zscore.fit_transform(data)

# --- Output Hasil ---
print("Data Asli:")
print(data)

print("\nSetelah Min-Max (Range 0-1):")
print(data_minmax)

print("\nSetelah Z-Score (Standardized):")
print(data_zscore)

# 4. Perbandingan Jarak Euclidean antara baris ke-0 dan baris ke-1
dist_asli = euclidean(data[0], data[1])
dist_minmax = euclidean(data_minmax[0], data_minmax[1])

print("\n--- Perbandingan Jarak ---")
print(f"Jarak Euclidean (data asli)  : {dist_asli:,.2f}")
print(f"Jarak Euclidean (Min-Max)    : {dist_minmax:.4f}")

Data Asli:
[[       2  2000000]
 [       5  7000000]
 [       3  5000000]
 [       8 12000000]]

Setelah Min-Max (Range 0-1):
[[0.         0.        ]
 [0.5        0.5       ]
 [0.16666667 0.3       ]
 [1.         1.        ]]

Setelah Z-Score (Standardized):
[[-1.09108945 -1.23624508]
 [ 0.21821789  0.13736056]
 [-0.65465367 -0.41208169]
 [ 1.52752523  1.5109662 ]]

--- Perbandingan Jarak ---
Jarak Euclidean (data asli)  : 5,000,000.00
Jarak Euclidean (Min-Max)    : 0.7071


In [9]:
import numpy as np
from sklearn.metrics import jaccard_score

def simple_matching_coefficient(p, q):
    """Menghitung SMC untuk dua vektor biner"""
    p = np.array(p)
    q = np.array(q)

    # m11: Keduanya bernilai 1
    # m00: Keduanya bernilai 0
    m11 = np.sum((p == 1) & (q == 1))
    m00 = np.sum((p == 0) & (q == 0))
    total = len(p)

    return (m11 + m00) / total

# Data Contoh (Vektor Biner)
p = [1, 0, 1, 1, 0]
q = [1, 0, 0, 1, 1]

# 1. Menghitung SMC
smc = simple_matching_coefficient(p, q)

# 2. Menghitung Jaccard secara Manual
# Jaccard mengabaikan m00 (negative matches)
m11 = np.sum((np.array(p) == 1) & (np.array(q) == 1))
m10 = np.sum((np.array(p) == 1) & (np.array(q) == 0))
m01 = np.sum((np.array(p) == 0) & (np.array(q) == 1))

jaccard_manual = m11 / (m11 + m10 + m01)

# 3. Menghitung Jaccard dengan Scikit-Learn
jaccard_sklearn = jaccard_score(p, q, average='binary')

# --- Output ---
print(f"Simple Matching Coefficient (SMC): {smc:.2f}") # Hasil: 0.60
print(f"Jaccard (Manual)                 : {jaccard_manual:.2f}") # Hasil: 0.50
print(f"Jaccard (Sklearn)                : {jaccard_sklearn:.2f}") # Hasil: 0.50

Simple Matching Coefficient (SMC): 0.60
Jaccard (Manual)                 : 0.50
Jaccard (Sklearn)                : 0.50


In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# 1. Kumpulan dokumen (Corpus)
documents = [
    "data mining machine learning",
    "machine learning data mining",
    "artificial intelligence",
    "deep learning neural network"
]

# 2. Konversi teks menjadi vektor TF-IDF
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)

# 3. Hitung Cosine Similarity antar semua dokumen
# similarity_matrix akan menghasilkan skor 0 sampai 1
similarity_matrix = cosine_similarity(tfidf_matrix)

# --- Output Hasil ---
print("Cosine Similarity Matrix:")
print(similarity_matrix.round(3))

print("\nFitur (Kosakata yang terdaftar):")
print(vectorizer.get_feature_names_out())

# 4. Mencari dokumen yang paling mirip dengan dokumen pertama (indeks 0)
# Kita menggunakan argsort()[-2] karena indeks [-1] adalah dokumen itu sendiri (skor 1.0)
most_similar_idx = similarity_matrix[0].argsort()[-2]

print(f"\nAnalisis:")
print(f"Dokumen 0: '{documents[0]}'")
print(f"Dokumen {most_similar_idx} paling mirip dengan dokumen 0")
print(f"Isi Dokumen {most_similar_idx}: '{documents[most_similar_idx]}'")
print(f"Skor Kemiripan: {similarity_matrix[0][most_similar_idx]:.3f}")

Cosine Similarity Matrix:
[[1.    1.    0.    0.146]
 [1.    1.    0.    0.146]
 [0.    0.    1.    0.   ]
 [0.146 0.146 0.    1.   ]]

Fitur (Kosakata yang terdaftar):
['artificial' 'data' 'deep' 'intelligence' 'learning' 'machine' 'mining'
 'network' 'neural']

Analisis:
Dokumen 0: 'data mining machine learning'
Dokumen 1 paling mirip dengan dokumen 0
Isi Dokumen 1: 'machine learning data mining'
Skor Kemiripan: 1.000


In [11]:
import numpy as np
from collections import Counter

def knn_predict(X_train, y_train, X_test, k=3):
    """Prediksi dengan k-NN menggunakan Euclidean distance"""
    predictions = []

    for test_point in X_test:
        # 1. Hitung jarak Euclidean ke semua titik data latih (X_train)
        distances = []
        for i, train_point in enumerate(X_train):
            # Rumus Euclidean: sqrt(sum((x1 - x2)^2))
            dist = np.sqrt(np.sum((test_point - train_point)**2))
            distances.append((dist, y_train[i]))

        # 2. Urutkan berdasarkan jarak terkecil (ascending)
        distances.sort(key=lambda x: x[0])

        # 3. Ambil k tetangga terdekat
        k_neighbors = distances[:k]

        # 4. Ambil label dari k tetangga tersebut
        k_labels = [neighbor[1] for neighbor in k_neighbors]

        # 5. Majority voting: Cari label yang paling sering muncul
        most_common = Counter(k_labels).most_common(1)[0][0]
        predictions.append(most_common)

    return np.array(predictions)

# --- Contoh Penggunaan: Klasifikasi Bunga Iris Sederhana ---

# X_train: Fitur (misal: panjang & lebar sepal)
X_train = np.array([
    [5.1, 3.5],
    [4.9, 3.0],
    [6.2, 3.4],
    [5.9, 3.0]
])

# y_train: Label (0=setosa, 1=versicolor)
y_train = np.array([0, 0, 1, 1])

# X_test: Data baru yang ingin diprediksi
X_test = np.array([
    [5.0, 3.2],
    [6.0, 3.2]
])

# Eksekusi Prediksi
predictions = knn_predict(X_train, y_train, X_test, k=3)

print(f"Hasil prediksi label: {predictions}")
# Output yang diharapkan: [0 1]

Hasil prediksi label: [0 1]


In [12]:
import pandas as pd
from sklearn.metrics import jaccard_score
from scipy.spatial.distance import pdist, squareform

# 1. Membuat DataFrame dari Data Transaksi
data = {
    'Produk_A': [1, 1, 0, 1],
    'Produk_B': [0, 1, 1, 0],
    'Produk_C': [1, 0, 1, 0]
}
df = pd.DataFrame(data, index=['Pelanggan 1', 'Pelanggan 2', 'Pelanggan 3', 'Pelanggan 4'])

print("--- Data Transaksi ---")
print(df)

# 2. Menghitung Jaccard Similarity antar baris (Pelanggan)
# pdist menghitung jarak, jadi kita gunakan (1 - jarak) untuk mendapatkan similarity
jaccard_distances = pdist(df.values, metric='jaccard')
jaccard_sim_matrix = 1 - squareform(jaccard_distances)

# 3. Masukkan ke dalam DataFrame agar rapi
sim_df = pd.DataFrame(
    jaccard_sim_matrix,
    index=df.index,
    columns=df.index
)

print("\n--- Matriks Kemiripan Jaccard ---")
print(sim_df.round(2))

# 4. Ambil rekomendasi untuk Pelanggan 1
p1_similarity = sim_df['Pelanggan 1'].drop('Pelanggan 1') # Hapus diri sendiri
most_similar_user = p1_similarity.idxmax()
similarity_score = p1_similarity.max()

print(f"\nKesimpulan:")
print(f"Pelanggan yang paling mirip dengan Pelanggan 1 adalah {most_similar_user}")
print(f"Tingkat kemiripan: {similarity_score:.2f}")

--- Data Transaksi ---
             Produk_A  Produk_B  Produk_C
Pelanggan 1         1         0         1
Pelanggan 2         1         1         0
Pelanggan 3         0         1         1
Pelanggan 4         1         0         0

--- Matriks Kemiripan Jaccard ---
             Pelanggan 1  Pelanggan 2  Pelanggan 3  Pelanggan 4
Pelanggan 1         1.00         0.33         0.33          0.5
Pelanggan 2         0.33         1.00         0.33          0.5
Pelanggan 3         0.33         0.33         1.00          0.0
Pelanggan 4         0.50         0.50         0.00          1.0

Kesimpulan:
Pelanggan yang paling mirip dengan Pelanggan 1 adalah Pelanggan 4
Tingkat kemiripan: 0.50


In [13]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Data Rating (0 berarti belum beli/rating)
# Baris: Pelanggan, Kolom: Produk (A, B, C)
ratings = np.array([
    [5, 0, 4], # Pelanggan 1 memberi rating tinggi
    [4, 5, 0], # Pelanggan 2
    [0, 2, 5], # Pelanggan 3
    [2, 0, 0]  # Pelanggan 4 memberi rating rendah
])

sim = cosine_similarity(ratings)
print("Matriks Kemiripan Cosine (Lebih detail dibanding Jaccard):")
print(sim.round(2))

Matriks Kemiripan Cosine (Lebih detail dibanding Jaccard):
[[1.   0.49 0.58 0.78]
 [0.49 1.   0.29 0.62]
 [0.58 0.29 1.   0.  ]
 [0.78 0.62 0.   1.  ]]
